// <auto-generated />
using System;
using Import_Export_Company.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Import_Export_Company.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529094933_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Import_Export_Company.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Delivery_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Customer_name = "Đại lý Thế Giới Số",
                            Delivery_address = "Đống Đa, Hà Nội",
                            Email = "contact@tgs.vn",
                            Phone = "0988111222"
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Financial_Vouchers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Payment_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Reference_id")
                        .HasColumnType("integer");

                    b.Property<string>("Reference_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<string>("Voucher_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Financial_Vouchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20000m,
                            Payment_date = new DateTime(2026, 5, 26, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(1134),
                            Payment_method = "BankTransfer",
                            Reference_id = 1,
                            Reference_type = "PurchaseOrder",
                            Type = "PAYMENT",
                            User_id = 4,
                            Voucher_number = "FV-2026-0001"
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Import_Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bill_of_lading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Commercial_invoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Customs_declaration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Document_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Eta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Etd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purchase_Order_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Purchase_Order_id");

                    b.ToTable("Import_Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bill_of_lading = "BOL-0001",
                            Commercial_invoice = "CI-0001",
                            Customs_declaration = "CD-0001",
                            Document_url = "https://docs.example.com/imports/1",
                            Eta = new DateTime(2026, 6, 1, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(851),
                            Etd = new DateTime(2026, 5, 22, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(848),
                            Purchase_Order_id = 1
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Reserved_quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Warehouse_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Warehouse_id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Product_id = 2,
                            Quantity = 50,
                            Reserved_quantity = 5,
                            Warehouse_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Product_id = 3,
                            Quantity = 30,
                            Reserved_quantity = 2,
                            Warehouse_id = 1
                        },
                        new
                        {
                            Id = 3,
                            Product_id = 2,
                            Quantity = 20,
                            Reserved_quantity = 0,
                            Warehouse_id = 2
                        },
                        new
                        {
                            Id = 4,
                            Product_id = 3,
                            Quantity = 15,
                            Reserved_quantity = 1,
                            Warehouse_id = 2
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory_Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("Reference_id")
                        .HasColumnType("integer");

                    b.Property<string>("Transaction_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<int>("WareHouse_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("User_id");

                    b.HasIndex("WareHouse_id");

                    b.ToTable("Inventory_Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2026, 5, 29, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(712),
                            Product_id = 2,
                            Quantity = 50,
                            Reference_id = 1,
                            Transaction_type = "IMPORT",
                            User_id = 1,
                            WareHouse_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2026, 5, 29, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(715),
                            Product_id = 3,
                            Quantity = 30,
                            Reference_id = 1,
                            Transaction_type = "IMPORT",
                            User_id = 1,
                            WareHouse_id = 1
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2026, 5, 29, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(717),
                            Product_id = 2,
                            Quantity = 5,
                            Reference_id = 1,
                            Transaction_type = "RESERVE",
                            User_id = 2,
                            WareHouse_id = 1
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Partner_Debts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Paid_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Partner_id")
                        .HasColumnType("integer");

                    b.Property<string>("Partner_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Remaining_debt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_debt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Partner_Debts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Paid_amount = 0m,
                            Partner_id = 1,
                            Partner_type = "Customer",
                            Remaining_debt = 7000m,
                            Total_debt = 7000m
                        },
                        new
                        {
                            Id = 2,
                            Paid_amount = 20000m,
                            Partner_id = 1,
                            Partner_type = "Supplier",
                            Remaining_debt = 30000m,
                            Total_debt = 50000m
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Barcode = "8901234567890",
                            Description = "Laptop cao cấp từ Dell",
                            Name = "Laptop Dell XPS 15",
                            Sku = "LAP-DELL-01",
                            Unit = "Cái",
                            Volume = 0.1m,
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "8901234567891",
                            Description = "Điện thoại thông minh cao cấp từ Apple",
                            Name = "iPhone 15 Pro Max 256GB",
                            Sku = "IPHONE-15-PRM",
                            Unit = "Cái",
                            Volume = 0.05m,
                            Weight = 0.2m
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Order_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Purchase_Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Purchase_Order_id");

                    b.ToTable("Purchase_Order_Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Product_id = 2,
                            Purchase_Order_id = 1,
                            Quantity = 10,
                            Unit_price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Product_id = 3,
                            Purchase_Order_id = 1,
                            Quantity = 5,
                            Unit_price = 3000m
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Created_by")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expected_Delivery")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Po_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Supplier_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Created_by");

                    b.HasIndex("Supplier_id");

                    b.ToTable("Purchase_Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = 1,
                            Currency = "USD",
                            Expected_Delivery = new DateTime(2026, 6, 3, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(757),
                            Order_Date = new DateTime(2026, 5, 19, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(750),
                            Po_Number = "PO-2026-0001",
                            Status = "SHIPPING",
                            Supplier_id = 1,
                            Total_Amount = 50000m
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản trị viên toàn quyền",
                            Role_name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nhân viên kinh doanh",
                            Role_name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thủ kho",
                            Role_name = "Warehouse"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kế toán",
                            Role_name = "Accountant"
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Order_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Sales_Order_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Sales_Order_id");

                    b.ToTable("Sales_Order_Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Product_id = 2,
                            Quantity = 2,
                            Sales_Order_id = 1,
                            Unit_price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Product_id = 3,
                            Quantity = 1,
                            Sales_Order_id = 1,
                            Unit_price = 3000m
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Created_by")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Customer_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("So_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Warehouse_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Created_by");

                    b.HasIndex("Customer_id");

                    b.HasIndex("Warehouse_id");

                    b.ToTable("Sales_Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = 2,
                            Currency = "USD",
                            Customer_id = 1,
                            Order_Date = new DateTime(2026, 5, 27, 9, 49, 33, 62, DateTimeKind.Utc).AddTicks(881),
                            So_Number = "SO-2026-0001",
                            Status = "PENDING",
                            Total_Amount = 7000m,
                            Warehouse_id = 1
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Suppliers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Texas, USA",
                            Company_name = "Dell Technologies US",
                            Contact_name = "NMC",
                            Country = "USA",
                            Email = "partner@dell.com",
                            Phone = "1800123456"
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2026, 5, 29, 9, 49, 32, 649, DateTimeKind.Utc).AddTicks(212),
                            Department = "Ban Giám Đốc",
                            Email = "admin@company.com",
                            FullName = "Nguyễn Minh Chiến",
                            Password = "$2a$11$ungZzQNMURplBUa73PPESO0WW6TZTP3.02OE2BoeceAoeTQv16SUW",
                            PhoneNumber = "0900000001",
                            Status = "Active",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2026, 5, 29, 9, 49, 32, 787, DateTimeKind.Utc).AddTicks(325),
                            Department = "Kinh Doanh",
                            Email = "sales@company.com",
                            FullName = "N V Sales",
                            Password = "$2a$11$JGDEdfdVLmoDfl.K0bWQPOX31Ech0DR5UaLWV8Yx3ERQVR03CIXsO",
                            PhoneNumber = "0900000002",
                            Status = "Active",
                            UserName = "sales"
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2026, 5, 29, 9, 49, 32, 924, DateTimeKind.Utc).AddTicks(6954),
                            Department = "Kho Bãi",
                            Email = "kho@company.com",
                            FullName = "N V Kho",
                            Password = "$2a$11$/TGH8jmshOqW9YA4idsCa.NwhwbNxl3MKN9s4HYtPYb9wNk1fjqDC",
                            PhoneNumber = "0900000003",
                            Status = "Active",
                            UserName = "kho"
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2026, 5, 29, 9, 49, 33, 61, DateTimeKind.Utc).AddTicks(9449),
                            Department = "Kế Toán",
                            Email = "keToan@company.com",
                            FullName = "N V Kế Toán",
                            Password = "$2a$11$8fQF8IvS1PKb21M0UeW8POfYDslymHfny9tjBzTMAL6MUHo9HjgLC",
                            PhoneNumber = "0900000004",
                            Status = "Active",
                            UserName = "keToan"
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.WareHouses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WareHouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            Name = "Kho Tổng Miền Bắc",
                            PhoneNumber = "0243111222"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hải Phòng",
                            Name = "Kho Cảng Hải Phòng",
                            PhoneNumber = "0225111333"
                        });
                });

            modelBuilder.Entity("Import_Export_Company.Models.Financial_Vouchers", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("FinancialVouchers")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Import_Documents", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Purchase_Orders", "Purchase_Order")
                        .WithMany("ImportDocuments")
                        .HasForeignKey("Purchase_Order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase_Order");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("Inventorys")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.WareHouses", "WareHouse")
                        .WithMany("Inventorys")
                        .HasForeignKey("Warehouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory_Transactions", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.WareHouses", "WareHouse")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WareHouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Order_Details", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Purchase_Orders", "Purchase_Order")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("Purchase_Order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase_Order");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Orders", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("Created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Suppliers", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("Supplier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Order_Details", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Sales_Orders", "Sales_order")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("Sales_Order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sales_order");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Orders", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("SalesOrders")
                        .HasForeignKey("Created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Customers", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.WareHouses", "WareHouse")
                        .WithMany()
                        .HasForeignKey("Warehouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Import_Export_Company.Models.UserRole", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Roles", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Customers", b =>
                {
                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Products", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("Inventorys");

                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Orders", b =>
                {
                    b.Navigation("ImportDocuments");

                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Orders", b =>
                {
                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Suppliers", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Users", b =>
                {
                    b.Navigation("FinancialVouchers");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SalesOrders");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Import_Export_Company.Models.WareHouses", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("Inventorys");
                });
#pragma warning restore 612, 618
        }
    }
}
