// <auto-generated />
using System;
using Import_Export_Company.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Import_Export_Company.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Import_Export_Company.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Delivery_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Financial_Vouchers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Payment_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Reference_id")
                        .HasColumnType("integer");

                    b.Property<string>("Reference_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<string>("Voucher_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Financial_Vouchers");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Import_Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bill_of_lading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Commercial_invoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Customs_declaration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Document_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Eta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Etd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purchase_Order_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Purchase_Order_id");

                    b.ToTable("Import_Documents");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Reserved_quantity")
                        .HasColumnType("integer");

                    b.Property<int>("WareHouse_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("WareHouse_id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory_Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("Reference_id")
                        .HasColumnType("integer");

                    b.Property<string>("Transaction_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<int>("Warehouse_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("User_id");

                    b.HasIndex("Warehouse_id");

                    b.ToTable("Inventory_Transactions");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Partner_Debts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Paid_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Partner_id")
                        .HasColumnType("integer");

                    b.Property<string>("Partner_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Remaining_debt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_debt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Partner_Debts");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Order_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Purchase_Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Purchase_Order_id");

                    b.ToTable("Purchase_Order_Details");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Created_by")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expected_Delivery")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Po_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Supplier_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Created_by");

                    b.HasIndex("Supplier_id");

                    b.ToTable("Purchase_Orders");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Order_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Product_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Sales_order_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Sales_order_id");

                    b.ToTable("Sales_Order_Details");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Created_by")
                        .HasColumnType("integer");

                    b.Property<int>("Customer_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("So_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total_amount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Created_by");

                    b.HasIndex("Customer_id");

                    b.ToTable("Sales_Orders");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Suppliers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Import_Export_Company.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Import_Export_Company.Models.WareHouses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WareHouses");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Financial_Vouchers", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("FinancialVouchers")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Import_Documents", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Purchase_Orders", "Purchase_Order")
                        .WithMany("ImportDocuments")
                        .HasForeignKey("Purchase_Order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase_Order");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("Inventorys")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.WareHouses", "WareHouse")
                        .WithMany("Inventorys")
                        .HasForeignKey("WareHouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Inventory_Transactions", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.WareHouses", "WareHouse")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("Warehouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Order_Details", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Purchase_Orders", "Purchase_Order")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("Purchase_Order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase_Order");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Orders", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("Created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Suppliers", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("Supplier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Order_Details", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Products", "Product")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Sales_Orders", "Sales_order")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("Sales_order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sales_order");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Orders", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("SalesOrders")
                        .HasForeignKey("Created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Customers", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Import_Export_Company.Models.UserRole", b =>
                {
                    b.HasOne("Import_Export_Company.Models.Roles", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Import_Export_Company.Models.Users", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Customers", b =>
                {
                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Products", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("Inventorys");

                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Purchase_Orders", b =>
                {
                    b.Navigation("ImportDocuments");

                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Sales_Orders", b =>
                {
                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Suppliers", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("Import_Export_Company.Models.Users", b =>
                {
                    b.Navigation("FinancialVouchers");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SalesOrders");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Import_Export_Company.Models.WareHouses", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("Inventorys");
                });
#pragma warning restore 612, 618
        }
    }
}
